Fixed dtype error in `se3.py` that came up in unit tests
facebookresearch/theseus pull request #158
Opened 2022-04-13 14:43 UTC by joeaortiz

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-13 15:56 UTC, luisenp approved these changes
Thanks for the fix! LGTM, just curious if `where` wouldn't accept a scalar tensor rather than having to call `full`.

2022-04-13 16:29 UTC, mhmukadam approved these changes

2022-04-13 17:18 UTC, fantaosha commented
> Thanks for the fix! LGTM, just curious if `where` wouldn't accept a scalar tensor rather than having to call `full`.

That's also what I thought. How about 
`torch.tensor(-1/12.0, dtype=sine_by_theta.dtype, device=sine_by_theta.device)`.

2022-04-13 17:27 UTC, fantaosha requested changes

2022-04-13 17:27 UTC, fantaosha commented on theseus/geometry/se3.py
> +            )
I just tested.
<pre><code>minus_one_by_twelve = torch.tensor(-1 / 12.0, 
                                   dtype=sine_by_theta.dtype, 
                                   device=since_by_theta.device)</code></pre>
should work for `torch.where()`.

2022-04-13 17:27 UTC, fantaosha commented on theseus/geometry/se3.py
> +            )
Same here.

2022-04-14 07:07 UTC, fantaosha approved these changes

2022-04-14 11:34 UTC, merged