Add normalization to Lie group
facebookresearch/theseus pull request #227
Opened 2022-07-06 18:33 UTC by fantaosha

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-06 19:21 UTC, luisenp requested changes
LGTM. We should add some simple tests for non-euclidean groups. For example, start with a bunch of random tensors, normalize, then check that group check holds; do this for batch size 1 and > 1.

2022-07-06 19:59 UTC, fantaosha commented on theseus/geometry/vector.py
> +    def normalize(matrix: torch.Tensor) -> torch.Tensor:
Replaced `matrix` with `data`.

2022-07-06 21:27 UTC, merged

2022-07-07 14:08 UTC, mhmukadam commented on theseus/geometry/manifold.py
> +    def normalize(data: torch.Tensor) -> torch.Tensor:
Is normalize supposed to be `@abc.abstractmethod` with the `Manifold` version doing `pass`?

2022-07-07 14:14 UTC, mhmukadam commented on theseus/geometry/manifold.py
> +    def normalize(data: torch.Tensor) -> torch.Tensor:
Same question for `_data_check`.