Add se3.left_act()
facebookresearch/theseus pull request #412
Opened 2023-01-01 20:58 UTC by fantaosha

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-01-06 22:16 UTC, mhmukadam approved these changes

2023-01-12 16:17 UTC, luisenp requested changes
LGTM. Some small comments to address.

2023-01-12 16:17 UTC, luisenp commented on theseus/geometry/functional/se3.py
> +        raise ValueError("Inconsistent shape for the matrix.")
Add more explicit error message.

2023-01-12 16:17 UTC, luisenp commented on theseus/geometry/functional/se3.py
> +class LeftAct(lie_group.BinaryOperator):
Missing description of what this does (or reference).

2023-01-12 16:17 UTC, luisenp commented on theseus/geometry/functional/se3.py
> +def _left_act_backward_helper(group, matrix, grad_output) -> torch.Tensor:
Missing type information for input arguments.

2023-01-12 20:12 UTC, merged